language: node_js

node_js:
  - '6'

install:
  - npm install -g yarn
  - yarn

script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm cache clean
  - npm run lint
  - npm run build
  - npm test
